### PR TITLE
CF-1038 - Implement feeds-specific RBAC for publishing to terminator feeds

### PR DESCRIPTION
**Pull request by usnavi**
**NOTE:  Don't accept this PR until the ```cloudfeeds:customer_access_policy-publisher``` and ```cloudfeeds:billing-publisher``` exists in identity and this can be fully tested**

Enables the ability to require product feeds to require specific roles to POST to the feed.  Default role is the current
cloudfeeds:service-admin.

To enable a custom role, the attribute writeRole attribute is set in the productSchema node of of the product schema.

Roles can also be tested by adding the writeRole attribute to the atom node in the message samples.

### CODE REVIEW

**Comment by shintasmith** [comment]
Does the generateSamples XPL handles generating sample XML with the right writeRole?

**Comment by usnavi** [comment]
@shintasmith  - good catch!  I'll get on that.

**Comment by usnavi** [comment]
retest this please

**Comment by usnavi** [comment]
@shintasmith added the following:
- If a serviceCode has more than one role assigned to writeRole - throws an error.  writeRole across all events in a serviceCode must have the same writeRole
- Fixing sample generation to add writeRole to XML samples

**Comment by shintasmith** [comment]
lgtm

**Comment by shintasmith** [comment]
I will let @ChandraAddala review and merge

**Pull request merged**
