### PR TITLE
[SS-1215/CF-986] - Add attributes to ATOM feed

### PR DESCRIPTION
**Pull request by yogenyadav**

### CODE REVIEW

**Comment by scadams** [comment]
Looks good to me. :+1:

**Comment by usnavi** [comment]
ok to test.

**Comment by shintasmith** [comment]
looks good to me. @usnavi?

**Comment by usnavi** [comment]
@yogenyadav @scadams  - We'd have some puppet work which we'd like to test this week.  It would be easier if we weren't committed to deploying to staging this Thurs.  If this is pushed to staging on 6/18 & prod on 6/23 - does that work with your timeframes?  

If not, we can put our puppet stuff on hold do our standard weekly release.

**Comment by scadams** [comment]
Sure, 6/18 for staging and 6/23 for prod are fine with us.

Sean

**Pull request merged**
