### PR TITLE
Remove pricing and SLA content

### PR DESCRIPTION
**Pull request by meker12**

### CODE REVIEW

**Comment by meker12** [comment]
Removing pricing and SLA information per instructions from mgmt.

**Comment by usnavi** [comment]
ok to test

**Comment by meker12** [comment]
@usnavi Does ok to test mean -- merge, or someone on your team will merge?

**Comment by shintasmith** [comment]
@meker12 , it's a phrase for Jenkins (which polls this repo) to kick off some test jobs. Ignore it. :-)

**Pull request merged**
