### PR TITLE
CF-705 - JSON Feed example in 2.4.1.1 doesn't match XML example

### PR DESCRIPTION
**Pull request by usnavi**
- Fixing XML & JSON examples

@shintasmith noticed that the node key's didn't make no sense...and it turns out the XML was not correct.  I regenerated the XML & JSON for this.  @stanzikratel I'll close your PR and replace it with this.

### CODE REVIEW

**Comment by shintasmith** [comment]
@usnavi, how about the other *.xml files in the same directory. For example: AtomContentElementExample.xml looks strange too. The event element has default namespace but the default namespace is not core/events.

**Comment by stanzikratel** [comment]
@shintasmith I can go ahead and fix the namespace in the other files if you guys provide me with the correct one.

**Comment by usnavi** [comment]
sure, I can cut-n-paste the data from the Feed file to the other example files.

**Comment by shintasmith** [comment]
yup, whatever works. :-) 

@stanzikratel, in the future, if you need samples like that, you can always hit the live Feeds Service :-), as long as we have the feature already deployed in Staging or Test.

**Comment by stanzikratel** [comment]
@shintasmith that sounds good :-)

**Comment by usnavi** [comment]
OK, attempted to fix any issues in the samples directory.

**Comment by shintasmith** [comment]
lgtm

**Pull request merged**
