### PR TITLE
CF-1326/B-90718 add new flavorIds to CBD

### PR DESCRIPTION
**Pull request by 404pilot**
**Flavor ID**                            | **Flavor Name** |
| ------------------------------ | ---------------------------------------- 
| hadoop-aws-sd-8                | Managed AWS Medium Dense-Storage Instance 
| hadoop-aws-sd-16               | Managed AWS Large Dense-Storage Instance 
| hadoop-aws-sd-30               | Managed AWS XL Dense-Storage Instance    
| hadoop-aws-sd-60               | Managed AWS 2XL Dense-Storage Instance   
| hadoop-aws-sd-120              | Managed AWS 4XL Dense-Storage Instance   
| hadoop-aws-sd-240              | Managed AWS 8XL Dense-Storage Instance   
|                                |                                          
| hadoop-aws-io-30               | Managed AWS XL High I/O Instance         
| hadoop-aws-io-60               | Managed AWS 2XL High I/O Instance        
| hadoop-aws-io-120              | Managed AWS 4XL High I/O Instance        
| hadoop-aws-io-240              | Managed AWS 8XL High I/O Instance        
|                                |                                          
| hadoop-aws-gp-8                | Managed AWS Large Master Node Instance   
| hadoop-aws-gp-16               | Managed AWS XLarge Master Node Instance  
| hadoop-aws-gp-32               | Managed AWS 2XLarge Master Node Instance 
| hadoop-aws-gp-64               | Managed AWS 4XLarge Master Node Instance 
| hadoop-aws-gp-160              | Managed AWS 10XLarge Master Node Instance

### CODE REVIEW

**Comment by shintasmith** [comment]
ok to test

**Comment by 404pilot** [comment]
For supporting aws big data, we also need new DCs added to core schema.

Just want to know, are y'all going to do the update or expecting UMS to do it?

**Comment by usnavi** [comment]
@404pilot  - we'll probably be doing that sometime before the end of the month.

**Comment by usnavi** [comment]
@VinnyQ  - please accept this PR and include it in the new release, when you are ready.

**Pull request merged**
