### PR TITLE
CF-1294: added rackspaceCDNSslCertificate

### PR DESCRIPTION
**Pull request by 404pilot**
As a UMS Developer
I want to create update the Rackspace CDN product schema in the Cloud feed repository
So that a new Rackspace CDN event can be collected for SSL Certificate

### CODE REVIEW

**Comment by usnavi** [comment]
ok to test

**Comment by usnavi** [comment]
lgtm.  we'll accept once 101.1 moves out of In QE

**Comment by shintasmith** [comment]
@404pilot, we are looking at Oct 15 date to our Staging env for this change. FYI.

**Comment by shintasmith** [comment]
@404pilot, sorry not Oct 15, but Oct 22.

**Comment by 404pilot** [comment]
@usnavi @shintasmith 

thanks for the information

**Comment by shintasmith** [comment]
merging in

**Pull request merged**
