### PR TITLE
CF-1016: dbaas: Updated assert for isHAInstance

### PR DESCRIPTION
**Pull request by ChandraAddala**

### CODE REVIEW

**Comment by shintasmith** [comment]
lgtm

**Comment by shintasmith** [comment]
@404pilot, we had to update the xpathAssertion for isHAInstance. Just FYI.

**Comment by shintasmith** [comment]
lgtm

**Comment by 404pilot** [comment]
@shintasmith @ChandraAddala 

I tried to understand the change, but I am stuck.

My guess is if `isHAInstance` is not specified in the event, then `not(@isHAInstance)`  will yield false. Is that correct?

Thanks.

**Comment by shintasmith** [comment]
I think what happened was ```not(@isHAInstance)``` checks for the existence of attribute ```@isHAInstance``` instead of testing for the boolean value.

**Pull request merged**
