### PR TITLE
CF-1293: Additional feeds to support Billing.

### PR DESCRIPTION
**Pull request by yogirackspace**
These are new additional feeds to support Billing Discounts, MRR.

### CODE REVIEW

**Comment by usnavi** [comment]
ok to test

**Comment by usnavi** [comment]
Hi @yogirackspace  - Your comments mention adding new feeds to the repo, but the ```allfeeds.wadl``` was not updated.  Also, if you want a new feed, you'll need talk to the product manager, @joesavak, as there is other work which must be done on our end.  You can also check out https://one.rackspace.com/display/cloudfeeds/New+Feed+Questionaire+for+Publishers

However, the new schemas you defined can be added to existing feeds, if the publishers & subscribers are OK with that.  The ```allfeeds.wadl``` will need to be updated as well, but we can help you out with that.

**Comment by yogirackspace** [comment]
They are new feed entries added to Billing Feed. Probably I should have been explicit. There is already an entry in alludes for Billing. That I believe is sufficient


Tests also locally pass. Thanks for the help.


Regards


?Yogeshwar Srikrishnan
Senior Enterprise Architect
[http://600a2794aa4ab5bae6bd-8d3014ab8e4d12d3346853d589a26319.r53.cf1.rackcdn.com/signatures/images/rackspace_logo.png]

yogesh.srikrishnan@rackspace.com
________________________________

**Comment by usnavi** [comment]
@yogirackspace  - thanks for the info.

Another thing: we've recently updated all existing events on the ```billing/events``` feeds to require the ```cloudfeeds:billing-publisher``` role.  (See, https://github.com/rackerlabs/standard-usage-schemas/blob/master/sample_product_schemas/billing.xml#L6) I think you'll want the same role for these events, right?

**Comment by yogirackspace** [comment]
?That should be fine. Thanks Greg.


Regards


Yogeshwar Srikrishnan
Senior Enterprise Architect
[http://600a2794aa4ab5bae6bd-8d3014ab8e4d12d3346853d589a26319.r53.cf1.rackcdn.com/signatures/images/rackspace_logo.png]

yogesh.srikrishnan@rackspace.com
________________________________

**Comment by usnavi** [comment]
@yogirackspace - I assume you'll eventually be updating this Pull Request?  Cloud Feeds is going into sustaining mode soon, so probably best to get this finalized this week.

**Comment by yogirackspace** [comment]
Sorry what do you like me to update? I think it had everything that was needed. I never got an email asking anything to be updated.

**Comment by usnavi** [comment]
No worries!  I made a comment about not having ```writeRole=cloudfeeds:billing-publisher``` role set for your new events.  All other events on the ```billing/events``` feed have it.  (See, https://github.com/rackerlabs/standard-usage-schemas/blob/master/sample_product_schemas/billing.xml#L6) 

This setting requires a publisher to have the given role when publisher the event.  It's more restrictive than allowing any ```cloudfeeds:service-admin``` to publish the event.

**Comment by yogirackspace** [comment]
Thanks for the help. I have done the needed changes and have recommitted. Could you guys try now?

**Comment by usnavi** [comment]
retest this please

**Comment by usnavi** [comment]
@yogirackspace - looks good.  We'll accept this after our staging deploy on Thurs.

**Comment by shintasmith** [comment]
we had finished our Staging deploy successfully, this is now ready to merge in

**Pull request merged**
