### PR TITLE
adding writeRole description CF-1173

### PR DESCRIPTION
**Pull request by stanzikratel**
Added a description of the writeRole attribute to the publisher's guide

### CODE REVIEW

**Comment by usnavi** [comment]
we'll have to hold out on this @stanzikratel   @shintasmith had some comments on my PR regarding writeRole and I want to make sure that's finalized before we document it.

**Comment by stanzikratel** [comment]
@usnavi sounds good. I'll wait until I hear from you guys on how I should proceed

**Comment by usnavi** [comment]
lgtm - @shintasmith once you merge https://github.com/rackerlabs/standard-usage-schemas/pull/503 please review this as well.

**Comment by shintasmith** [comment]
lgtm

**Pull request merged**
