### PR TITLE
CF-1299: fix generate-rst, add more rst files

### PR DESCRIPTION
**Pull request by shintasmith**
I figured out the problem of Maven skipping some task/plugin. Maven doesn't like it when you have multiple of the same plugin bound to the same phase. It will skip one of them. This PR combines the 2 of maven-antrun-plugin definition to one, but have 2 different executions for 2 different phases (this is how you control the order). 

I also added a task to copy the generated *.rst files to the api-docs directory.

### CODE REVIEW

**Comment by shintasmith** [comment]
@usnavi, pls review.

cc: @meker12, @stanzikratel, this should complete the automation of the *.rst files generation

**Comment by usnavi** [comment]
Looks like some generated files got checked in?  Other than that, lgtm.

**Comment by shintasmith** [comment]
They do need to be checked in under ```api-docs/dev-guide/api-operations/methods/``` directory. @meker12 had checked in some of the other ones previously

**Comment by usnavi** [comment]
thanks @shintasmith.  Feel free to merge after the build passes.

**Pull request merged**
