### PR TITLE
CF-1193: added note that max size of POST requests is 2 MB

### PR DESCRIPTION
**Pull request by stanzikratel**

### CODE REVIEW

**Comment by usnavi** [comment]
lgtm.  I'll let @shintasmith merge.

**Comment by shintasmith** [comment]
@stanzikratel, is there a story associated with this? If so, we probably should title the PR with that story. 

Other than that, it looks good.

**Comment by stanzikratel** [comment]
@shintasmith I just added the number of the story. It's CF-1193. Thanks!

**Comment by stanzikratel** [comment]
@shintasmith I just added the number of the story. It's CF-1193. Thanks!

**Comment by shintasmith** [comment]
lgtm, thx!

**Pull request merged**
