### PR TITLE
Cf 1172: add kibana dashboard content 

### PR DESCRIPTION
**Pull request by stanzikratel**

### CODE REVIEW

**Comment by stanzikratel** [comment]
@shintasmith and @usnavi I recreated the pull request for CF-1172 - add Cloud Feeds kibana dashboard.

**Comment by usnavi** [comment]
lgtm.

**Comment by shintasmith** [comment]
@stanzikratel, this PR needs to be rebase before we can merge it. Content looks good to me.

**Comment by stanzikratel** [comment]
@shintasmith @usnavi I fixed the merge conflict (it was in pom.xml) and checked in my changes. Everything should be good to merge now.

**Pull request merged**
