### PR TITLE
CF-1149: add /customer_accounts feed

### PR DESCRIPTION
**Pull request by shintasmith**
Add /customer_accounts feed. Not exposed to observers.

### CODE REVIEW

**Comment by shintasmith** [comment]
@usnavi, @ChandraAddala, please review.

**Comment by ChandraAddala** [comment]
@shintasmith "Not exposed to observers." What does this mean? Why do we have to do this?

**Comment by shintasmith** [comment]
I mean, the feed is not published to external customers. By "observers" I meant the family of "observers" roles: identity:user-admin, admin, observers, and cloudfeeds:observers roles.

**Comment by usnavi** [comment]
lgtm.  @ChandraAddala can merge.

**Pull request merged**
